import base from "./UI.js";

const REDESIGN_CSS = String.raw`
:root{--ss-surface:#090b0e;--ss-surface-2:#0e1116;--ss-border:rgba(255,191,0,.30);--ss-gold:#ffbf00;--ss-green:#12c96b}
body.ss-redesign{background:#050607;color:#f8f8f8}
body.ss-redesign .wrap{max-width:1540px;padding:18px 22px}
body.ss-redesign .top{min-height:84px;display:grid;grid-template-columns:minmax(260px,1fr) auto auto auto;gap:18px;align-items:center;flex-wrap:nowrap;padding:14px 18px;border-radius:20px;background:linear-gradient(180deg,rgba(19,21,24,.98),rgba(6,7,9,.98));border:1px solid var(--ss-border);box-shadow:0 18px 44px rgba(0,0,0,.46)}
body.ss-redesign .top .brand{display:flex;min-width:0;gap:12px;align-items:center;flex-wrap:nowrap}
body.ss-redesign .top .brandText{min-width:0}body.ss-redesign .top .title{font-size:25px;line-height:1.05;white-space:nowrap}
body.ss-redesign .top .sub,body.ss-redesign .top .brandHelp{display:none!important}
body.ss-redesign .top .logo{width:58px;height:58px;min-width:58px;display:block}body.ss-redesign .top .logo img{height:58px!important;width:58px!important;object-fit:contain!important}body.ss-redesign .top .logo:before{display:none}
#ssProductNav{display:flex;gap:10px;align-items:center;justify-content:center;min-width:0}#ssProductNav .btn{min-height:46px;padding:10px 16px;border-radius:13px;font-size:14px;background:#0b0e12;border-color:rgba(255,191,0,.32)}#ssProductNav #btnMusic{background:linear-gradient(180deg,#ffd352,#ffb900);color:#0b0b0b;border-color:#ffd352;box-shadow:0 8px 24px rgba(255,191,0,.18)}#ssProductNav #btnStudio{background:linear-gradient(180deg,rgba(18,201,107,.20),rgba(18,201,107,.10));border-color:rgba(18,201,107,.55)}
#ssAccountWrap{position:relative;display:flex;align-items:center}#ssAccountButton{min-height:44px;padding:10px 15px;border-radius:13px;white-space:nowrap}#ssAccountMenu{display:none;position:absolute;right:0;top:calc(100% + 10px);width:245px;padding:10px;z-index:10050;border-radius:16px;border:1px solid rgba(255,191,0,.34);background:rgba(9,11,14,.99);box-shadow:0 24px 60px rgba(0,0,0,.65)}#ssAccountWrap.open #ssAccountMenu{display:grid;gap:7px}#ssAccountMenu .btn{width:100%;text-align:left;justify-content:flex-start;min-height:40px;background:rgba(255,255,255,.04);border-color:rgba(255,191,0,.18)}
body.ss-redesign #authRow{margin:0!important;width:auto!important;justify-content:flex-end;gap:8px;flex-wrap:nowrap}body.ss-redesign #authRow .chip{max-width:235px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
body.ss-redesign .grid{grid-template-columns:300px minmax(0,1fr);gap:18px;margin-top:18px}body.ss-redesign .grid>.card{border-radius:20px;border-color:rgba(255,191,0,.24);background:linear-gradient(180deg,#0b0e12,#07090c);box-shadow:0 18px 48px rgba(0,0,0,.38)}body.ss-redesign .grid>.card:first-child h3{padding:16px 16px 12px;border-bottom:0;color:#fff;font-size:18px;letter-spacing:0;text-transform:none}body.ss-redesign .grid>.card:first-child .body{max-height:none;overflow:visible;padding:0 16px 18px}
#ssNowArt{display:block;width:100%;aspect-ratio:1/1;object-fit:cover;border-radius:16px;border:1px solid rgba(255,191,0,.24);margin:0 0 14px;background:#0d1014;box-shadow:0 12px 30px rgba(0,0,0,.38)}body.ss-redesign #npTitle{font-size:19px;line-height:1.2}body.ss-redesign #npMeta{font-size:12px;margin-top:4px}body.ss-redesign #player{height:40px;margin-top:14px!important}body.ss-redesign .grid>.card:first-child .controls .btn,body.ss-redesign .grid>.card:first-child .controls .pill{border-radius:11px}
body.ss-redesign .rightHeader{padding:14px 16px;display:flex;gap:10px;align-items:center;border-bottom:1px solid rgba(255,191,0,.16);background:rgba(7,9,12,.82)}body.ss-redesign .rightHeader .crumbs{order:2;flex:1 1 100%;min-height:0}body.ss-redesign .rightHeader .row.ssDiscoveryNav{order:1;display:grid;grid-template-columns:minmax(260px,1fr) repeat(3,minmax(110px,150px));gap:10px;width:100%;align-items:center}body.ss-redesign .rightHeader .row.ssDiscoveryNav #search{grid-column:1;width:100%;min-width:0;min-height:44px;background:#11151b;border-color:rgba(255,255,255,.16);font-size:14px}body.ss-redesign .rightHeader .row.ssDiscoveryNav #btnHome,body.ss-redesign .rightHeader .row.ssDiscoveryNav #btnSubject,body.ss-redesign .rightHeader .row.ssDiscoveryNav #btnAll{min-height:44px;font-size:14px;border-radius:12px}body.ss-redesign .rightHeader .row.ssDiscoveryNav #btnHome{background:linear-gradient(180deg,rgba(18,201,107,.23),rgba(18,201,107,.12));border-color:rgba(18,201,107,.58)}body.ss-redesign #btnTrending{display:none!important}body.ss-redesign #btnStudio[style*='display: none']{display:none!important}
body.ss-redesign .grid>.card:last-child>.body{padding:16px 18px 24px;max-height:none;overflow:visible}body.ss-redesign.ss-home-mode #filterWrap,body.ss-redesign.ss-home-mode #modeChips{display:none!important}
.ssHero{position:relative;min-height:230px;display:grid;grid-template-columns:minmax(0,1.25fr) minmax(300px,.75fr);overflow:hidden;border:1px solid rgba(255,191,0,.20);border-radius:20px;background:radial-gradient(circle at 75% 30%,rgba(26,88,126,.25),transparent 42%),linear-gradient(135deg,#151c27 0%,#0a0e15 52%,#11131a 100%);margin-bottom:22px}.ssHeroCopy{padding:34px 36px;position:relative;z-index:2}.ssHero h1{margin:0;font-size:46px;line-height:.98;letter-spacing:-1.7px;max-width:650px;color:#fff}.ssHero h1 span{color:var(--ss-gold)}.ssHero p{font-size:17px;color:#d0d4da;margin:16px 0 18px}.ssHeroCta{min-height:46px;padding:10px 20px;border:0;border-radius:11px;font-weight:900;font-size:15px;background:linear-gradient(180deg,#ffd550,#ffb800);color:#090909;cursor:pointer}.ssHeroVisual{position:relative;display:flex;align-items:center;justify-content:center;gap:0;padding:20px 28px 20px 0;min-width:0}.ssHeroVisual img{width:145px;aspect-ratio:1/1;object-fit:cover;border-radius:18px;border:1px solid rgba(255,255,255,.12);box-shadow:0 20px 45px rgba(0,0,0,.52);position:relative}.ssHeroVisual img:nth-child(1){transform:translateX(34px) rotate(-8deg);z-index:1;opacity:.72}.ssHeroVisual img:nth-child(2){z-index:3;width:175px}.ssHeroVisual img:nth-child(3){transform:translateX(-34px) rotate(8deg);z-index:1;opacity:.72}.ssMetrics{position:absolute;right:14px;bottom:12px;z-index:4;display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.ssMetric{font-size:10px;padding:6px 9px;border-radius:999px;background:rgba(3,5,7,.78);border:1px solid rgba(255,255,255,.12);color:#e8edf2}
.ssSection{margin:20px 0 26px}.ssSectionHead{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.ssSectionHead h2{margin:0;font-size:22px;color:#fff;letter-spacing:-.3px}.ssSectionHead button{border:1px solid rgba(255,191,0,.28);background:transparent;color:#fff;border-radius:999px;padding:7px 12px;font-weight:800;cursor:pointer}.ssSubjectGrid{display:grid;grid-template-columns:repeat(10,minmax(0,1fr));gap:10px}.ssSubjectCard{min-height:118px!important;padding:14px 8px!important;border-radius:14px!important;display:flex!important;flex-direction:column;align-items:center;justify-content:center;gap:8px;text-align:center;font-size:11px!important;font-weight:900!important;color:#fff!important;background:linear-gradient(180deg,#172032,#10151f)!important;border:1px solid rgba(255,191,0,.25)!important;cursor:pointer;box-shadow:none!important}.ssSubjectCard:nth-child(8n+1){background:linear-gradient(180deg,#12366d,#0b2247)!important;border-color:#2e71ca!important}.ssSubjectCard:nth-child(8n+2){background:linear-gradient(180deg,#6b2427,#421416)!important;border-color:#b14548!important}.ssSubjectCard:nth-child(8n+3){background:linear-gradient(180deg,#0a5d3d,#063b27)!important;border-color:#159667!important}.ssSubjectCard:nth-child(8n+4){background:linear-gradient(180deg,#49308b,#2a1b58)!important;border-color:#7158c7!important}.ssSubjectCard:nth-child(8n+5){background:linear-gradient(180deg,#11616b,#0b3a41)!important;border-color:#26949e!important}.ssSubjectCard:nth-child(8n+6){background:linear-gradient(180deg,#77401d,#45230f)!important;border-color:#a86533!important}.ssSubjectCard:nth-child(8n+7){background:linear-gradient(180deg,#6d5612,#44350b)!important;border-color:#a98522!important}.ssSubjectCard:nth-child(8n+8){background:linear-gradient(180deg,#233c61,#16253b)!important;border-color:#426494!important}.ssSubjectIcon{font-size:28px;line-height:1}.ssAlbumGrid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:12px}.ssAlbumGrid .albumCard{width:100%!important;min-width:0!important;max-width:none!important;margin:0!important;border-radius:15px!important;background:#090b0e!important;border-color:rgba(255,191,0,.20)!important}.ssAlbumGrid .albumCover{width:100%!important;aspect-ratio:1/1!important;height:auto!important;object-fit:cover!important;border-radius:13px!important}.ssMoreTile{min-height:118px;border:1px solid rgba(255,191,0,.24);border-radius:14px;background:#15191f;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:7px;font-weight:900;cursor:pointer;color:#fff}.ssMoreTile span:first-child{font-size:28px}
@media(max-width:1240px){body.ss-redesign .top{grid-template-columns:minmax(220px,1fr) auto auto}.top #authRow{grid-column:1/-1;justify-self:end}#ssProductNav .btn{padding:9px 11px;font-size:12px}.ssSubjectGrid{grid-template-columns:repeat(5,minmax(0,1fr))}.ssAlbumGrid{grid-template-columns:repeat(4,minmax(0,1fr))}}
@media(max-width:980px){body.ss-redesign{padding-bottom:92px}body.ss-redesign .wrap{padding:10px 10px 18px}body.ss-redesign .top{display:grid;grid-template-columns:1fr auto;grid-template-areas:'brand account' 'products products' 'auth auth';gap:9px;padding:10px;border-radius:16px;min-height:0}body.ss-redesign .top .brand{grid-area:brand;display:flex;width:auto;min-width:0}body.ss-redesign .top .logo{width:44px;height:44px;min-width:44px}.top .logo img{width:44px!important;height:44px!important}body.ss-redesign .top .title{font-size:17px;white-space:normal;line-height:1.08}#ssProductNav{grid-area:products;justify-content:flex-start;overflow-x:auto;padding-bottom:2px;scrollbar-width:none}#ssProductNav::-webkit-scrollbar{display:none}#ssProductNav .btn{flex:0 0 auto;min-height:40px;font-size:11px;padding:8px 11px}#ssAccountWrap{grid-area:account;align-self:start}#ssAccountButton{min-height:40px;padding:8px 10px;font-size:12px}#ssAccountButton:after{display:none;content:none}body.ss-redesign #authRow{grid-area:auth;width:100%!important;justify-content:flex-start;overflow-x:auto;flex-wrap:nowrap}body.ss-redesign #authRow .chip{max-width:210px}body.ss-redesign .grid{display:block;margin-top:10px}body.ss-redesign .grid>.card:first-child{display:none!important}body.ss-redesign .grid>.card:last-child{display:block;width:100%}body.ss-redesign .rightHeader{padding:9px;display:block}body.ss-redesign .rightHeader .crumbs{display:none}body.ss-redesign .rightHeader .row.ssDiscoveryNav{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}body.ss-redesign .rightHeader .row.ssDiscoveryNav #search{grid-column:1/-1;grid-row:1;min-height:42px;font-size:13px}body.ss-redesign .rightHeader .row.ssDiscoveryNav #btnHome,body.ss-redesign .rightHeader .row.ssDiscoveryNav #btnSubject,body.ss-redesign .rightHeader .row.ssDiscoveryNav #btnAll{grid-row:2;min-height:40px;font-size:11px;padding:6px}body.ss-redesign .grid>.card:last-child>.body{padding:10px 10px 20px}.ssHero{display:block;min-height:0;margin-bottom:16px}.ssHeroCopy{padding:22px 18px}.ssHero h1{font-size:34px}.ssHero p{font-size:14px;margin:10px 0 15px}.ssHeroVisual{display:none}.ssMetrics{position:static;margin:0 18px 16px;justify-content:flex-start}.ssSection{margin:16px 0 22px}.ssSectionHead h2{font-size:19px}.ssSubjectGrid{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.ssSubjectCard,.ssMoreTile{min-height:92px!important}.ssSubjectIcon{font-size:24px}.ssAlbumGrid{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}#ssAccountMenu{position:fixed;left:12px;right:12px;top:78px;width:auto;max-height:70vh;overflow:auto}}
`;

const REDESIGN_JS = String.raw`
(function(){
  var VERSION='2026-09-11-shell-v1',homeProcessing=false;
  function $(id){return document.getElementById(id)}
  function human(s){return String(s||'').replace(/_/g,' ').replace(/\s+/g,' ').trim()}
  function iconFor(name){var n=String(name||'').toLowerCase();if(n.indexOf('math')>=0)return '∑';if(n==='sat'||n.indexOf('sat ')>=0)return 'A+';if(n.indexOf('biomolecule')>=0)return '🧪';if(n.indexOf('micro')>=0)return '🔬';if(n.indexOf('biology')>=0)return '🧬';if(n.indexOf('chem')>=0)return '⚗️';if(n.indexOf('anatom')>=0)return '🫁';if(n.indexOf('food')>=0)return '🍎';if(n.indexOf('spanish')>=0||n.indexOf('french')>=0||n.indexOf('language')>=0)return '🌐';if(n.indexOf('college')>=0||n.indexOf('life after')>=0)return '💼';if(n.indexOf('drug')>=0)return '💊';if(n.indexOf('gospel')>=0)return '✦';if(n.indexOf('entertain')>=0)return '🎬';return '📘'}
  function subjectName(raw){var s=human(raw),names=['Anatomy & Physiology','Anatomy_Physiology','Food & Nutrition','Food_and_Nutrition','BioMolecules','Entertainment','Microbiology','Chemistry','Biology','Gospel','Math','SAT'];for(var i=0;i<names.length;i++){if(s.toLowerCase().indexOf(names[i].toLowerCase())>=0)return human(names[i])}return s.replace(/^[^A-Za-z0-9]+\s*/,'')}function addClass(el,c){if(el&&!el.classList.contains(c))el.classList.add(c)}function move(id,parent){var el=$(id);if(el&&parent&&el.parentNode!==parent)parent.appendChild(el);return el}
  function buildShell(){document.body.classList.add('ss-redesign');var top=document.querySelector('.top');if(!top)return;var auth=$('authRow'),sub=top.querySelector('.sub');if(sub)sub.style.display='none';var product=$('ssProductNav');if(!product){product=document.createElement('nav');product.id='ssProductNav';product.setAttribute('aria-label','SaySayMusic products');if(auth)top.insertBefore(product,auth);else top.appendChild(product)}['btnMusic','btnLearningGames','btnMusicBuilder','btnGlobal','btnStudio'].forEach(function(id){move(id,product)});var account=$('ssAccountWrap');if(!account){account=document.createElement('div');account.id='ssAccountWrap';var ab=document.createElement('button');ab.id='ssAccountButton';ab.className='btn';ab.type='button';ab.textContent='Account';ab.setAttribute('aria-expanded','false');var menu=document.createElement('div');menu.id='ssAccountMenu';account.appendChild(ab);account.appendChild(menu);if(auth)top.insertBefore(account,auth);else top.appendChild(account);ab.onclick=function(e){e.stopPropagation();var open=account.classList.toggle('open');ab.setAttribute('aria-expanded',open?'true':'false')};document.addEventListener('click',function(e){if(!account.contains(e.target)){account.classList.remove('open');ab.setAttribute('aria-expanded','false')}})}var menu=$('ssAccountMenu');var labels={btnUpgradeTop:'Upgrade plan',btnBilling:'Billing & Account',btnContact:'Contact & Support',btnInstallApp:'Install SaySayMusic',btnPortal:'Consultant Portal'};['btnUpgradeTop','btnBilling','btnContact','btnInstallApp','btnPortal'].forEach(function(id){var b=move(id,menu);if(b&&labels[id])b.textContent=labels[id]});var clean={btnHome:'Home',btnSubject:'Subjects',btnAll:'All',btnStudio:'Studio'};Object.keys(clean).forEach(function(id){var b=$(id);if(b)b.textContent=clean[id]});var rh=document.querySelector('.rightHeader');if(rh){var row=rh.querySelector('.row');if(row){addClass(row,'ssDiscoveryNav');['search','btnHome','btnSubject','btnAll'].forEach(function(id){move(id,row)})}}var tr=$('btnTrending');if(tr)tr.style.display='none';ensureNowArt()}
  function ensureNowArt(){var np=$('npTitle');if(!np||$('ssNowArt'))return;var img=document.createElement('img');img.id='ssNowArt';img.alt='Current album artwork';np.parentNode.insertBefore(img,np);updateNowArt()}
  function updateNowArt(){var target=$('ssNowArt');if(!target)return;var title=String(($('npTitle')&&$('npTitle').textContent)||'').trim().toLowerCase(),nothing=!title||title==='nothing playing';var album=window.__ssOpenAlbum||null,bmp=document.querySelector('#bottomMiniPlayer img,.bmpArt');var albumSrc=album&&(album.cover_url||album.cover||'');var src=nothing?'https://audio.saysaymusic.com/Logo_New1.png':(albumSrc||(bmp&&bmp.src)||'https://audio.saysaymusic.com/Logo_New1.png');if(target.src!==src)target.src=src}
  function makeSection(title,actionText,actionFn){var sec=document.createElement('section');sec.className='ssSection';var head=document.createElement('div');head.className='ssSectionHead';var h=document.createElement('h2');h.textContent=title;head.appendChild(h);if(actionText){var b=document.createElement('button');b.type='button';b.textContent=actionText+'  →';b.onclick=actionFn;head.appendChild(b)}sec.appendChild(head);return sec}
  function makeHero(cards){var hero=document.createElement('section');hero.className='ssHero';var copy=document.createElement('div');copy.className='ssHeroCopy';copy.innerHTML='<h1>Make Learning <span>Unforgettable</span></h1><p>Educational music for every learner.</p>';var cta=document.createElement('button');cta.className='ssHeroCta';cta.type='button';cta.textContent='Explore Subjects';cta.onclick=function(){var b=$('btnSubject');if(b)b.click()};copy.appendChild(cta);hero.appendChild(copy);var vis=document.createElement('div');vis.className='ssHeroVisual';var imgs=[];(cards||[]).slice(0,3).forEach(function(c){var im=c.querySelector('img');if(im&&im.src)imgs.push(im.src)});if(!imgs.length)imgs.push('https://audio.saysaymusic.com/Logo_New1.png');while(imgs.length<3)imgs.push(imgs[imgs.length-1]);imgs.slice(0,3).forEach(function(src){var im=document.createElement('img');im.src=src;im.alt='SaySayMusic album artwork';vis.appendChild(im)});hero.appendChild(vis);var metrics=document.createElement('div');metrics.className='ssMetrics';['🎓 3,000+ Educational Songs','▥ Multiple Subjects','👥 K–12 Support','⌂ School, Home & District'].forEach(function(t){var m=document.createElement('span');m.className='ssMetric';m.textContent=t;metrics.appendChild(m)});hero.appendChild(metrics);return hero}
  function processHome(){var wrap=$('homeWrap');if(!wrap||homeProcessing)return;var isHome=wrap.style.display!=='none'&&getComputedStyle(wrap).display!=='none';document.body.classList.toggle('ss-home-mode',isHome);if(!isHome)return;if(wrap.querySelector('.ssHero')){updateNowArt();return}var kids=Array.prototype.slice.call(wrap.children),exploreRow=null;for(var i=0;i<kids.length;i++){var txt=String(kids[i].textContent||'').replace(/\s+/g,' ').trim().toLowerCase();if(txt.indexOf('explore subjects')>=0){exploreRow=kids[i].nextElementSibling;break}}var cards=Array.prototype.slice.call(wrap.querySelectorAll('.albumCard'));if(!exploreRow||!exploreRow.children.length||!cards.length)return;var bioPanel=wrap.querySelector('.bioMoleculesPanel');homeProcessing=true;try{var subjects=Array.prototype.slice.call(exploreRow.children).filter(function(x){return x&&String(x.textContent||'').trim()});var featured=cards.slice(0,6),recent=cards.slice(6,12);if(!recent.length)recent=[];wrap.innerHTML='';wrap.appendChild(makeHero(featured));var subSec=makeSection('Browse by Subject','View All Subjects',function(){var b=$('btnSubject');if(b)b.click()});var sg=document.createElement('div');sg.className='ssSubjectGrid';subjects.slice(0,9).forEach(function(chip){var raw=subjectName(String(chip.textContent||'').trim());chip.className='ssSubjectCard';chip.innerHTML='';var ico=document.createElement('span');ico.className='ssSubjectIcon';ico.textContent=iconFor(raw);var tx=document.createElement('span');tx.textContent=raw;chip.appendChild(ico);chip.appendChild(tx);sg.appendChild(chip)});if(subjects.length>9){var more=document.createElement('button');more.className='ssMoreTile';more.type='button';more.innerHTML='<span>•••</span><span>More</span>';more.onclick=function(){var b=$('btnSubject');if(b)b.click()};sg.appendChild(more)}subSec.appendChild(sg);wrap.appendChild(subSec);if(bioPanel)wrap.appendChild(bioPanel);var feat=makeSection('Featured Albums','View All',function(){var b=$('btnAll');if(b)b.click()});var fg=document.createElement('div');fg.className='ssAlbumGrid';featured.forEach(function(c){fg.appendChild(c)});feat.appendChild(fg);wrap.appendChild(feat);var rec=makeSection('Recently Added','View All',function(){var b=$('btnAll');if(b)b.click()});var rg=document.createElement('div');rg.className='ssAlbumGrid';recent.forEach(function(c){rg.appendChild(c)});rec.appendChild(rg);wrap.appendChild(rec);wrap.dataset.ssModern=VERSION;updateNowArt()}finally{homeProcessing=false}}
  function sync(){buildShell();processHome();updateNowArt()}
  function boot(){sync();if(new URLSearchParams(location.search).get('login')==='1'){setTimeout(function(){var account=$('ssAccountWrap'),login=null;if(account)account.classList.add('open');var buttons=document.querySelectorAll('#ssAccountMenu button');for(var i=0;i<buttons.length;i++){if(/^log in$/i.test(String(buttons[i].textContent||'').trim())){login=buttons[i];break}}if(login)login.click()},500)}var home=$('homeWrap');if(home)new MutationObserver(function(){setTimeout(processHome,20)}).observe(home,{childList:true,subtree:false,attributes:true,attributeFilter:['style']});var mini=$('bottomMiniPlayer');if(mini)new MutationObserver(function(){updateNowArt()}).observe(mini,{childList:true,subtree:true,attributes:true,attributeFilter:['src']});var auth=$('authRow');if(auth)new MutationObserver(function(){setTimeout(buildShell,10)}).observe(auth,{childList:true,subtree:true});var mainBody=document.querySelector('.grid>.card:last-child>.body');if(mainBody)new MutationObserver(function(){setTimeout(function(){processHome();updateNowArt()},25)}).observe(mainBody,{childList:true,subtree:true});window.addEventListener('resize',processHome);setTimeout(sync,250);setTimeout(sync,900);setTimeout(sync,1800)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
`;

function enhanceHtml(html){if(!html||typeof html!=="string")return html;if(html.includes('id="saysay-redesign-css"'))return html;html=html.replace('</head>','<style id="saysay-redesign-css">'+REDESIGN_CSS+'</style></head>');html=html.replace('</body>','<script id="saysay-redesign-js">'+REDESIGN_JS+'</script></body>');return html}

export default{async fetch(request,env,ctx){const response=await base.fetch(request,env,ctx);const ct=response.headers.get("content-type")||"";if(!ct.toLowerCase().includes("text/html"))return response;const html=await response.text();const headers=new Headers(response.headers);headers.delete("content-length");headers.set("cache-control","no-store");return new Response(enhanceHtml(html),{status:response.status,statusText:response.statusText,headers})}};
